name: Container Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  discover-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.scan.outputs.folders }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find Dockerfiles
        id: scan
        run: |
          # 1) Find all subdirs that have a Dockerfile at the top level
          FOLDERS=$(find . -mindepth 1 -maxdepth 1 -type d -exec test -e "{}/Dockerfile" \; -print | sed 's|^\./||')
      
          # 2) If nothing found, set an empty array
          if [ -z "$FOLDERS" ]; then
            echo "No Dockerfiles found."
            JSON_ARRAY="[]"
          else
            # Convert multiple lines to space-delimited
            FOLDERS_SINGLE_LINE=$(echo "$FOLDERS" | paste -sd " " -)
      
            # Convert space-delimited list to JSON array with jq
            JSON_ARRAY=$(echo "$FOLDERS_SINGLE_LINE" | jq -R -s 'split(" ")')
          fi
      
          # 3) Remove any newlines from the final JSON array
          #    so GitHub Actions can parse it correctly
          JSON_ARRAY_ONE_LINE=$(echo "$JSON_ARRAY" | tr -d '\n')
      
          # 4) Export to outputs
          echo "folders=$JSON_ARRAY_ONE_LINE" >> $GITHUB_OUTPUT
      

  build-test-and-push:
    runs-on: ubuntu-latest
    needs: discover-dockerfiles

    strategy:
      fail-fast: false
      matrix:
        container-folder: ${{ fromJson(needs.discover-dockerfiles.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Short Commit SHA
        id: get_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.container-folder }}
          push: false
          load: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}-${{ matrix.container-folder }}
            ghcr.io/${{ github.repository }}:latest-${{ matrix.container-folder }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max

      - name: Push Docker Image
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/main' && success()
        with:
          context: ${{ matrix.container-folder }}
          file: ${{ matrix.container-folder }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}-${{ matrix.container-folder }}
            ghcr.io/${{ github.repository }}:latest-${{ matrix.container-folder }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max
