name: Container Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  discover-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find_dockerfiles.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Discover Dockerfiles
        id: find_dockerfiles
        run: |
          echo "Searching for Dockerfiles in subdirectories..."
          docker_dirs=$(find . -mindepth 2 -type f -name Dockerfile -exec dirname {} \; | sed 's|^\./||' | sort | uniq)
          echo "Found docker directories:"
          echo "$docker_dirs"
          if [ -z "$docker_dirs" ]; then
            matrix="[]"
          else
            matrix=$(echo "$docker_dirs" | jq -R -s -c 'split("\n")[:-1]')
          fi
          echo "Generated matrix: $matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build-test-and-push:
    runs-on: ubuntu-latest
    needs: discover-dockerfiles
    strategy:
      fail-fast: false
      matrix:
        container-folder: ${{ fromJson(needs.discover-dockerfiles.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Short Commit SHA
        id: get_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.container-folder }}
          push: false
          load: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}-${{ matrix.container-folder }}
            ghcr.io/${{ github.repository }}:latest-${{ matrix.container-folder }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max

      - name: Push Docker Image
        if: github.ref == 'refs/heads/main' && success()
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.container-folder }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}-${{ matrix.container-folder }}
            ghcr.io/${{ github.repository }}:latest-${{ matrix.container-folder }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max
